
package partida;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.Arrays;
import urjc.poo.lingo.Clases.AlmacenUsuarios;
import urjc.poo.lingo.Clases.Usuario;
import java.util.*;
import javax.swing.JTextField;
import java.util.Random;


public class partidaSeisLetras extends javax.swing.JFrame {

    private AlmacenUsuarios almacenUsuarios;
    Usuario usuario1;
    Usuario usuario2;
    int palabras;
    int contadorFila = 0;
    int contadorEnabled = 6;
    int contadorFila2 = 0;
    List<String> palabra;
    boolean pistaPalabraNoUsada = true;
    boolean pistaLetraNoUsada = true;
    JTextField[] gridLetras = new JTextField[30];

    
    
    public partidaSeisLetras(AlmacenUsuarios a, Usuario u1,Usuario u2, int numeroPalabras, String pala) {
        initComponents();
        almacenUsuarios = a;
        usuario1 = u1;
        usuario2 = u2;
        palabras = numeroPalabras;
        palabra = Arrays.asList(pala.split(""));
        this.setLocationRelativeTo(null);
        gridLetras[0] = letra11;//0
        gridLetras[1] = letra12;
        gridLetras[2] = letra13;
        gridLetras[3] = letra14;
        gridLetras[4] = letra15;
        gridLetras[5] = letra16;//6
        gridLetras[6] = letra21;
        gridLetras[7] = letra22;
        gridLetras[8] = letra23;
        gridLetras[9] = letra24;
        gridLetras[10] = letra25;
        gridLetras[11] = letra26;//12
        gridLetras[12] = letra31;
        gridLetras[13] = letra32;
        gridLetras[14] = letra33;
        gridLetras[15] = letra34;
        gridLetras[16] = letra35;
        gridLetras[17] = letra36;//18
        gridLetras[18] = letra41;
        gridLetras[19] = letra42;
        gridLetras[20] = letra43;
        gridLetras[21] = letra44;
        gridLetras[22] = letra45;
        gridLetras[23] = letra46;//24
        gridLetras[24] = letra51;
        gridLetras[25] = letra52;
        gridLetras[26] = letra53;
        gridLetras[27] = letra54;
        gridLetras[28] = letra55;
        gridLetras[29] = letra56;//30
    }
    
    public partidaSeisLetras(String pala){
        initComponents();
        palabra = Arrays.asList(pala.split(""));
        this.setLocationRelativeTo(null);
    }
    
    public partidaSeisLetras() {
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        letra12 = new javax.swing.JTextField();
        letra13 = new javax.swing.JTextField();
        letra11 = new javax.swing.JTextField();
        letra15 = new javax.swing.JTextField();
        letra16 = new javax.swing.JTextField();
        letra21 = new javax.swing.JTextField();
        letra22 = new javax.swing.JTextField();
        letra23 = new javax.swing.JTextField();
        letra14 = new javax.swing.JTextField();
        letra25 = new javax.swing.JTextField();
        letra26 = new javax.swing.JTextField();
        letra31 = new javax.swing.JTextField();
        letra32 = new javax.swing.JTextField();
        letra24 = new javax.swing.JTextField();
        letra33 = new javax.swing.JTextField();
        letra35 = new javax.swing.JTextField();
        letra36 = new javax.swing.JTextField();
        letra41 = new javax.swing.JTextField();
        letra42 = new javax.swing.JTextField();
        letra43 = new javax.swing.JTextField();
        letra44 = new javax.swing.JTextField();
        letra45 = new javax.swing.JTextField();
        letra46 = new javax.swing.JTextField();
        letra51 = new javax.swing.JTextField();
        letra34 = new javax.swing.JTextField();
        letra53 = new javax.swing.JTextField();
        letra52 = new javax.swing.JTextField();
        letra55 = new javax.swing.JTextField();
        letra56 = new javax.swing.JTextField();
        letra54 = new javax.swing.JTextField();
        comprobar = new javax.swing.JButton();
        pistaPalabra = new javax.swing.JButton();
        pistaLetra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        letra12.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra12.setToolTipText("");
        letra12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra12ActionPerformed(evt);
            }
        });
        letra12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra12KeyTyped(evt);
            }
        });

        letra13.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra13.setToolTipText("");
        letra13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra13ActionPerformed(evt);
            }
        });
        letra13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra13KeyTyped(evt);
            }
        });

        letra11.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra11.setToolTipText("");
        letra11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra11ActionPerformed(evt);
            }
        });
        letra11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra11KeyTyped(evt);
            }
        });

        letra15.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra15.setToolTipText("");
        letra15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra15ActionPerformed(evt);
            }
        });
        letra15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra15KeyTyped(evt);
            }
        });

        letra16.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra16.setToolTipText("");
        letra16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra16ActionPerformed(evt);
            }
        });
        letra16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra16KeyTyped(evt);
            }
        });

        letra21.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra21.setToolTipText("");
        letra21.setEnabled(false);
        letra21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra21ActionPerformed(evt);
            }
        });
        letra21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra21KeyTyped(evt);
            }
        });

        letra22.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra22.setToolTipText("");
        letra22.setEnabled(false);
        letra22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra22ActionPerformed(evt);
            }
        });
        letra22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra22KeyTyped(evt);
            }
        });

        letra23.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra23.setToolTipText("");
        letra23.setEnabled(false);
        letra23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra23ActionPerformed(evt);
            }
        });
        letra23.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra23KeyTyped(evt);
            }
        });

        letra14.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra14.setToolTipText("");
        letra14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra14ActionPerformed(evt);
            }
        });
        letra14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra14KeyTyped(evt);
            }
        });

        letra25.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra25.setToolTipText("");
        letra25.setEnabled(false);
        letra25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra25ActionPerformed(evt);
            }
        });
        letra25.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra25KeyTyped(evt);
            }
        });

        letra26.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra26.setToolTipText("");
        letra26.setEnabled(false);
        letra26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra26ActionPerformed(evt);
            }
        });
        letra26.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra26KeyTyped(evt);
            }
        });

        letra31.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra31.setToolTipText("");
        letra31.setEnabled(false);
        letra31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra31ActionPerformed(evt);
            }
        });
        letra31.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra31KeyTyped(evt);
            }
        });

        letra32.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra32.setToolTipText("");
        letra32.setEnabled(false);
        letra32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra32ActionPerformed(evt);
            }
        });
        letra32.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra32KeyTyped(evt);
            }
        });

        letra24.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra24.setToolTipText("");
        letra24.setEnabled(false);
        letra24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra24ActionPerformed(evt);
            }
        });
        letra24.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra24KeyTyped(evt);
            }
        });

        letra33.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra33.setToolTipText("");
        letra33.setEnabled(false);
        letra33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra33ActionPerformed(evt);
            }
        });
        letra33.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra33KeyTyped(evt);
            }
        });

        letra35.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra35.setToolTipText("");
        letra35.setEnabled(false);
        letra35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra35ActionPerformed(evt);
            }
        });
        letra35.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra35KeyTyped(evt);
            }
        });

        letra36.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra36.setToolTipText("");
        letra36.setEnabled(false);
        letra36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra36ActionPerformed(evt);
            }
        });
        letra36.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra36KeyTyped(evt);
            }
        });

        letra41.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra41.setToolTipText("");
        letra41.setEnabled(false);
        letra41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra41ActionPerformed(evt);
            }
        });
        letra41.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra41KeyTyped(evt);
            }
        });

        letra42.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra42.setToolTipText("");
        letra42.setEnabled(false);
        letra42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra42ActionPerformed(evt);
            }
        });
        letra42.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra42KeyTyped(evt);
            }
        });

        letra43.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra43.setToolTipText("");
        letra43.setEnabled(false);
        letra43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra43ActionPerformed(evt);
            }
        });
        letra43.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra43KeyTyped(evt);
            }
        });

        letra44.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra44.setToolTipText("");
        letra44.setEnabled(false);
        letra44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra44ActionPerformed(evt);
            }
        });
        letra44.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra44KeyTyped(evt);
            }
        });

        letra45.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra45.setToolTipText("");
        letra45.setEnabled(false);
        letra45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra45ActionPerformed(evt);
            }
        });
        letra45.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra45KeyTyped(evt);
            }
        });

        letra46.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra46.setToolTipText("");
        letra46.setEnabled(false);
        letra46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra46ActionPerformed(evt);
            }
        });
        letra46.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra46KeyTyped(evt);
            }
        });

        letra51.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra51.setToolTipText("");
        letra51.setEnabled(false);
        letra51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra51ActionPerformed(evt);
            }
        });
        letra51.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra51KeyTyped(evt);
            }
        });

        letra34.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra34.setToolTipText("");
        letra34.setEnabled(false);
        letra34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra34ActionPerformed(evt);
            }
        });
        letra34.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra34KeyTyped(evt);
            }
        });

        letra53.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra53.setToolTipText("");
        letra53.setEnabled(false);
        letra53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra53ActionPerformed(evt);
            }
        });
        letra53.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra53KeyTyped(evt);
            }
        });

        letra52.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra52.setToolTipText("");
        letra52.setEnabled(false);
        letra52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra52ActionPerformed(evt);
            }
        });
        letra52.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra52KeyTyped(evt);
            }
        });

        letra55.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra55.setToolTipText("");
        letra55.setEnabled(false);
        letra55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra55ActionPerformed(evt);
            }
        });
        letra55.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra55KeyTyped(evt);
            }
        });

        letra56.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra56.setToolTipText("");
        letra56.setEnabled(false);
        letra56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra56ActionPerformed(evt);
            }
        });
        letra56.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra56KeyTyped(evt);
            }
        });

        letra54.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        letra54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra54.setToolTipText("");
        letra54.setEnabled(false);
        letra54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra54ActionPerformed(evt);
            }
        });
        letra54.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letra54KeyTyped(evt);
            }
        });

        comprobar.setText("Comprobar");
        comprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobarActionPerformed(evt);
            }
        });

        pistaPalabra.setText("Pista de Palabra");
        pistaPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pistaPalabraActionPerformed(evt);
            }
        });

        pistaLetra.setText("Pista de Letra");
        pistaLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pistaLetraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(letra41, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(letra31, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(letra21, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(letra11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(letra51, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letra52, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letra42, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letra32, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(letra22, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(letra12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pistaLetra))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(letra33, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(letra43, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(letra53, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(letra23, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(letra13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letra14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letra24, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letra44, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letra34, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(letra54, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(letra55, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(letra56, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(letra15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(letra35, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(letra25, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(letra26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(letra16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(letra36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(letra45, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(32, 32, 32)
                                            .addComponent(letra46, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comprobar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pistaPalabra)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra21, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra22, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra23, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra25, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra26, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra24, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra31, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra32, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra33, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra34, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra35, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra36, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra46, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra45, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra44, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra43, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra42, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra41, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra51, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra52, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra53, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra54, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra55, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra56, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comprobar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pistaPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pistaLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void letra12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra12ActionPerformed

    }//GEN-LAST:event_letra12ActionPerformed

    private void letra12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra12KeyTyped
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra12.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra12KeyTyped

    private void letra13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra13ActionPerformed

    private void letra13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra13KeyTyped
       char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra13.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra13KeyTyped

    private void letra11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra11ActionPerformed

    private void letra11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra11KeyTyped
       char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra11.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra11KeyTyped

    private void letra15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra15ActionPerformed

    private void letra15KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra15KeyTyped
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra15.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra15KeyTyped

    private void letra16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra16ActionPerformed

    private void letra16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra16KeyTyped
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra16.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra16KeyTyped

    private void letra21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra21ActionPerformed

    private void letra21KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra21KeyTyped
       char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra21.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra21KeyTyped

    private void letra22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra22ActionPerformed

    private void letra22KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra22KeyTyped
       char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra22.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra22KeyTyped

    private void letra23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra23ActionPerformed

    private void letra23KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra23KeyTyped
       char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra23.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra23KeyTyped

    private void letra14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra14ActionPerformed

    private void letra14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra14KeyTyped
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra14.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra14KeyTyped

    private void letra25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra25ActionPerformed

    private void letra25KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra25KeyTyped
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra25.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra25KeyTyped

    private void letra26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra26ActionPerformed

    private void letra26KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra26KeyTyped
       char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra26.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra26KeyTyped

    private void letra31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra31ActionPerformed

    private void letra31KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra31KeyTyped
       char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra31.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra31KeyTyped

    private void letra32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra32ActionPerformed

    private void letra32KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra32KeyTyped
       char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra32.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra32KeyTyped

    private void letra24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra24ActionPerformed

    private void letra24KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra24KeyTyped
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra24.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra24KeyTyped

    private void letra33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra33ActionPerformed

    private void letra33KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra33KeyTyped
       char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra33.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra33KeyTyped

    private void letra35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra35ActionPerformed

    private void letra35KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra35KeyTyped
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra35.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra35KeyTyped

    private void letra36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra36ActionPerformed

    private void letra36KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra36KeyTyped
       char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra36.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra36KeyTyped

    private void letra41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra41ActionPerformed

    private void letra41KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra41KeyTyped
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra41.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra41KeyTyped

    private void letra42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra42ActionPerformed

    private void letra42KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra42KeyTyped
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra42.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra42KeyTyped

    private void letra43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra43ActionPerformed

    private void letra43KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra43KeyTyped
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra43.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra43KeyTyped

    private void letra44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra44ActionPerformed

    private void letra44KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra44KeyTyped
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra44.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra44KeyTyped

    private void letra45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra45ActionPerformed

    private void letra45KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra45KeyTyped
       char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra45.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra45KeyTyped

    private void letra46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra46ActionPerformed

    private void letra46KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra46KeyTyped
      char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra46.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra46KeyTyped

    private void letra51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra51ActionPerformed

    private void letra51KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra51KeyTyped
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra51.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra51KeyTyped

    private void letra34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra34ActionPerformed

    private void letra34KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra34KeyTyped
       char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra34.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra34KeyTyped

    private void letra53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra53ActionPerformed

    private void letra53KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra53KeyTyped
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra53.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra53KeyTyped

    private void letra52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra52ActionPerformed

    private void letra52KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra52KeyTyped
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra52.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra52KeyTyped

    private void letra55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra55ActionPerformed

    private void letra55KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra55KeyTyped
       char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra55.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra55KeyTyped

    private void letra56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra56ActionPerformed

    private void letra56KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra56KeyTyped
       char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra56.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra56KeyTyped

    private void letra54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra54ActionPerformed

    private void letra54KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letra54KeyTyped
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if(letra54.getText().length() >= 1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_letra54KeyTyped

    private void comprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobarActionPerformed

        String[] letras = new String[6];
        Boolean[] esIgual = new Boolean[6];
        for(int i = 0; i<6; i++) esIgual[i] = false;
        Boolean esIgualEntero = true;

        for(int i = 0; i<6; i++){
            JTextField aux = gridLetras[contadorFila2];
            String stringaux = aux.getText().toLowerCase();
            letras[i] = stringaux;
            contadorFila2+=1;
        }
        for(int i = 0; i<6; i++){
            if(palabra.contains(letras[i])){
                if(palabra.get(i).toLowerCase().equals(letras[i])){
                    gridLetras[contadorFila].setBackground(Color.green);
                    esIgual[i] = true;
                }else{
                    gridLetras[contadorFila].setBackground(Color.yellow);
                }
            }else{
                gridLetras[contadorFila].setBackground(Color.gray);
            }
            contadorFila+=1;
        }
        for(int i = 0; i<6 && esIgualEntero; i++){
            if(!esIgual[i]) esIgualEntero = false;
        }
        System.out.println(esIgualEntero.toString());

        for(int i = 0; i<6; i++){
            gridLetras[this.contadorEnabled].enable();
            contadorEnabled+=1;
        }

    }//GEN-LAST:event_comprobarActionPerformed

    private void pistaPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pistaPalabraActionPerformed
            if(pistaPalabraNoUsada){
            
            switch(contadorFila){
                case 0:
                    for(int i = 0; i<6; i++){
                        gridLetras[contadorFila].setBackground(Color.green);
                        gridLetras[contadorFila].setText(palabra.get(i).toUpperCase());
                        contadorFila+=1;
                    }
                    break;
                
                case 6:
                    for(int i = 0; i<6; i++){
                        gridLetras[contadorFila].setBackground(Color.green);
                        gridLetras[contadorFila].setText(palabra.get(i).toUpperCase());
                        contadorFila+=1;
                    }
                    break;
                    
                case 12:
                    for(int i = 0; i<6; i++){
                        gridLetras[contadorFila].setBackground(Color.green);
                        gridLetras[contadorFila].setText(palabra.get(i).toUpperCase());
                        contadorFila+=1;
                    }
                    break;
                
                case 18:
                    for(int i = 0; i<6; i++){
                        gridLetras[contadorFila].setBackground(Color.green);
                        gridLetras[contadorFila].setText(palabra.get(i).toUpperCase());
                        contadorFila+=1;
                    }
                    break;
                    
                case 24:
                    for(int i = 0; i<6; i++){
                        gridLetras[contadorFila].setBackground(Color.green);
                        gridLetras[contadorFila].setText(palabra.get(i).toUpperCase());
                        contadorFila+=1;
                    }
                    break;
            }
        }
        pistaPalabra.setEnabled(false);
        pistaPalabraNoUsada = false;
    }//GEN-LAST:event_pistaPalabraActionPerformed

    private void pistaLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pistaLetraActionPerformed
        Random r1 = new Random();
        int posicionLetraAleatoria = r1.nextInt(6);
        
        if(pistaLetraNoUsada){
            switch(contadorFila){
                case 0:
                    gridLetras[posicionLetraAleatoria].setText(palabra.get(posicionLetraAleatoria).toUpperCase());
                    gridLetras[posicionLetraAleatoria].setBackground(Color.green);
                    break;
                case 6:
                    gridLetras[posicionLetraAleatoria+6].setText(palabra.get(posicionLetraAleatoria).toUpperCase());
                    gridLetras[posicionLetraAleatoria+6].setBackground(Color.green);
                    break;
                case 12:
                    gridLetras[posicionLetraAleatoria+12].setText(palabra.get(posicionLetraAleatoria).toUpperCase());
                    gridLetras[posicionLetraAleatoria+12].setBackground(Color.green);
                    break;
                case 18:
                    gridLetras[posicionLetraAleatoria+18].setText(palabra.get(posicionLetraAleatoria).toUpperCase());
                    gridLetras[posicionLetraAleatoria+18].setBackground(Color.green);
                    break;
                case 24:
                    gridLetras[posicionLetraAleatoria+24].setText(palabra.get(posicionLetraAleatoria).toUpperCase());
                    gridLetras[posicionLetraAleatoria+24].setBackground(Color.green);
                    break;
            }
        }
        pistaLetra.setEnabled(false);
        pistaLetraNoUsada = false;
    }//GEN-LAST:event_pistaLetraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(partidaSeisLetras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(partidaSeisLetras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(partidaSeisLetras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(partidaSeisLetras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new partidaSeisLetras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comprobar;
    private javax.swing.JTextField letra11;
    private javax.swing.JTextField letra12;
    private javax.swing.JTextField letra13;
    private javax.swing.JTextField letra14;
    private javax.swing.JTextField letra15;
    private javax.swing.JTextField letra16;
    private javax.swing.JTextField letra21;
    private javax.swing.JTextField letra22;
    private javax.swing.JTextField letra23;
    private javax.swing.JTextField letra24;
    private javax.swing.JTextField letra25;
    private javax.swing.JTextField letra26;
    private javax.swing.JTextField letra31;
    private javax.swing.JTextField letra32;
    private javax.swing.JTextField letra33;
    private javax.swing.JTextField letra34;
    private javax.swing.JTextField letra35;
    private javax.swing.JTextField letra36;
    private javax.swing.JTextField letra41;
    private javax.swing.JTextField letra42;
    private javax.swing.JTextField letra43;
    private javax.swing.JTextField letra44;
    private javax.swing.JTextField letra45;
    private javax.swing.JTextField letra46;
    private javax.swing.JTextField letra51;
    private javax.swing.JTextField letra52;
    private javax.swing.JTextField letra53;
    private javax.swing.JTextField letra54;
    private javax.swing.JTextField letra55;
    private javax.swing.JTextField letra56;
    private javax.swing.JButton pistaLetra;
    private javax.swing.JButton pistaPalabra;
    // End of variables declaration//GEN-END:variables
}
